trigger: none
pr: none

name: Terraform values passed via pipeline

pool:
  vmImage: 'ubuntu-20.04'

variables:
- group: shilda-ci

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      **/*.tfvars
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-passing-values/hardcoded'
    command: 'init'
    backendServiceArm: 'Visual Studio Enterprise with MSDN(26f3dfe8-09e6-475f-b019-06857f15af9f)'
    environmentServiceNameAzureRM: 'Visual Studio Enterprise with MSDN(26f3dfe8-09e6-475f-b019-06857f15af9f)'
    backendAzureRmResourceGroupName: 'TheCodeManual'
    backendAzureRmStorageAccountName: 'thecodemanual'
    backendAzureRmContainerName: 'infra'
    backendAzureRmKey: 'tcm-terrafrom-hardcoded-values'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-passing-values/hardcoded'
    command: 'plan'
    backendServiceArm: 'Visual Studio Enterprise with MSDN(26f3dfe8-09e6-475f-b019-06857f15af9f)'
    environmentServiceNameAzureRM: 'Visual Studio Enterprise with MSDN(26f3dfe8-09e6-475f-b019-06857f15af9f)'
    backendAzureRmResourceGroupName: 'TheCodeManual'
    backendAzureRmStorageAccountName: 'thecodemanual'
    backendAzureRmContainerName: 'infra'
    backendAzureRmKey: 'tcm-terrafrom-hardcoded-values'
    commandOptions: -var="env=ci"

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-passing-values/hardcoded'
    command: 'apply'
    backendServiceArm: 'Visual Studio Enterprise with MSDN(26f3dfe8-09e6-475f-b019-06857f15af9f)'
    environmentServiceNameAzureRM: 'Visual Studio Enterprise with MSDN(26f3dfe8-09e6-475f-b019-06857f15af9f)'
    backendAzureRmResourceGroupName: 'TheCodeManual'
    backendAzureRmStorageAccountName: 'thecodemanual'
    backendAzureRmContainerName: 'infra'
    backendAzureRmKey: 'tcm-terrafrom-hardcoded-values'
    commandOptions: -auto-approve -var="env=ci"